{{{Hp, Fe, Cp[bar[UFv[{gO1}]], Hp, Fe[{gI2}]], FFS, 1, 1}, 
  {VWp, Fe, Cp[bar[UFv[{gO1}]], VWp, Fe[{gI2}]], FFV, 1, 1}, 
  {VZ, Fv, Cp[bar[UFv[{gO1}]], VZ, Fv[{gI2}]], FFV, 1, 1}}, 
 {{VWp, Ah, Cp[conj[Hp], VWp, Ah], SSV, 1, 1}, 
  {bar[Fd], Fu, Cp[conj[Hp], bar[Fd[{gI1}]], Fu[{gI2}]], FFS, 3, 1}, 
  {bar[Fe], Fv, Cp[conj[Hp], bar[Fe[{gI1}]], Fv[{gI2}]], FFS, 1, 1}, 
  {bar[gZ], gWp, Cp[conj[Hp], bar[gZ], gWp], GGS, 1, 1}, 
  {bar[gWpC], gZ, Cp[conj[Hp], bar[gWpC], gZ], GGS, 1, 1}, 
  {Hp, hh, Cp[conj[Hp], Hp, hh], SSS, 1, 1}, {VWp, hh, Cp[conj[Hp], VWp, hh], 
   SSV, 1, 1}, {VP, Hp, Cp[conj[Hp], VP, Hp], SSV, 1, 1}, 
  {VZ, Hp, Cp[conj[Hp], VZ, Hp], SSV, 1, 1}, {VWp, VP, Cp[conj[Hp], VWp, VP], 
   SVV, 1, 1}, {VZ, VWp, Cp[conj[Hp], VZ, VWp], SVV, 1, 1}, 
  {Ah, Ah, Cp[Hp, conj[Hp], Ah, Ah], SSSS, 1, 1/2}, 
  {hh, hh, Cp[Hp, conj[Hp], hh, hh], SSSS, 1, 1/2}, 
  {conj[Hp], Hp, Cp[Hp, conj[Hp], conj[Hp], Hp], SSSS, 1, 1}, 
  {VP, VP, Cp[Hp, conj[Hp], VP, VP], SSVV, 1, 1/2}, 
  {conj[VWp], VWp, Cp[Hp, conj[Hp], conj[VWp], VWp], SSVV, 1, 1}, 
  {VZ, VZ, Cp[Hp, conj[Hp], VZ, VZ], SSVV, 1, 1/2}}, 
 {{hh, Ah, Cp[Ah, hh, Ah], SSS, 1, 1/2}, 
  {bar[Fd], Fd, Cp[Ah, bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[Ah, bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[Ah, bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {bar[gWp], gWp, Cp[Ah, bar[gWp], gWp], GGS, 1, 1/2}, 
  {bar[gWpC], gWpC, Cp[Ah, bar[gWpC], gWpC], GGS, 1, 1/2}, 
  {VZ, hh, Cp[Ah, VZ, hh], SSV, 1, 1/2}, {conj[VWp], Hp, 
   Cp[Ah, conj[VWp], Hp], SSV, 1, 1}, {Ah, Ah, Cp[Ah, Ah, Ah, Ah], SSSS, 1, 
   1/2}, {hh, hh, Cp[Ah, Ah, hh, hh], SSSS, 1, 1/2}, 
  {conj[Hp], Hp, Cp[Ah, Ah, conj[Hp], Hp], SSSS, 1, 1}, 
  {conj[VWp], VWp, Cp[Ah, Ah, conj[VWp], VWp], SSVV, 1, 1}, 
  {VZ, VZ, Cp[Ah, Ah, VZ, VZ], SSVV, 1, 1/2}}, 
 {{Ah, Ah, Cp[hh, Ah, Ah], SSS, 1, 1/4}, {VZ, Ah, Cp[hh, VZ, Ah], SSV, 1, 
   1/2}, {bar[Fd], Fd, Cp[hh, bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[hh, bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[hh, bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {bar[gWp], gWp, Cp[hh, bar[gWp], gWp], GGS, 1, 1/2}, 
  {bar[gWpC], gWpC, Cp[hh, bar[gWpC], gWpC], GGS, 1, 1/2}, 
  {bar[gZ], gZ, Cp[hh, bar[gZ], gZ], GGS, 1, 1/2}, 
  {hh, hh, Cp[hh, hh, hh], SSS, 1, 1/4}, {conj[Hp], Hp, Cp[hh, conj[Hp], Hp], 
   SSS, 1, 1/2}, {conj[VWp], Hp, Cp[hh, conj[VWp], Hp], SSV, 1, 1}, 
  {conj[VWp], VWp, Cp[hh, conj[VWp], VWp], SVV, 1, 1/2}, 
  {VZ, VZ, Cp[hh, VZ, VZ], SVV, 1, 1/4}, {Ah, Ah, Cp[hh, hh, Ah, Ah], SSSS, 
   1, 1/2}, {hh, hh, Cp[hh, hh, hh, hh], SSSS, 1, 1/2}, 
  {conj[Hp], Hp, Cp[hh, hh, conj[Hp], Hp], SSSS, 1, 1}, 
  {conj[VWp], VWp, Cp[hh, hh, conj[VWp], VWp], SSVV, 1, 1}, 
  {VZ, VZ, Cp[hh, hh, VZ, VZ], SSVV, 1, 1/2}}, 
 {{bar[Fd], Fd, Cp[VG, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[Fu], Fu, Cp[VG, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[gG], gG, Cp[VG, bar[gG], gG], GGV, 3, 1/2}, 
  {VG, VG, Cp[VG, VG, VG], VVV, 3, 1/4}, {VG, VG, Cp[VG, VG, VG, VG], VVVV, 
   1, 1/2}}, {{bar[Fd], Fd, Cp[VP, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VP, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VP, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[gWp], gWp, Cp[VP, bar[gWp], gWp], GGV, 1, 1/2}, 
  {bar[gWpC], gWpC, Cp[VP, bar[gWpC], gWpC], GGV, 1, 1/2}, 
  {conj[Hp], Hp, Cp[VP, conj[Hp], Hp], SSV, 1, 1/2}, 
  {conj[VWp], Hp, Cp[VP, conj[VWp], Hp], SVV, 1, 1}, 
  {conj[VWp], VWp, Cp[VP, conj[VWp], VWp], VVV, 1, 1/2}, 
  {conj[Hp], Hp, Cp[VP, VP, conj[Hp], Hp], SSVV, 1, 1}, 
  {conj[VWp], VWp, Cp[VP, VP, conj[VWp], VWp], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZ, hh, Ah], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VZ, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZ, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZ, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fv], Fv, Cp[VZ, bar[Fv[{gI1}]], Fv[{gI2}]], FFV, 1, 1/2}, 
  {bar[gWp], gWp, Cp[VZ, bar[gWp], gWp], GGV, 1, 1/2}, 
  {bar[gWpC], gWpC, Cp[VZ, bar[gWpC], gWpC], GGV, 1, 1/2}, 
  {VZ, hh, Cp[VZ, VZ, hh], SVV, 1, 1/2}, {conj[Hp], Hp, Cp[VZ, conj[Hp], Hp], 
   SSV, 1, 1/2}, {conj[VWp], Hp, Cp[VZ, conj[VWp], Hp], SVV, 1, 1}, 
  {conj[VWp], VWp, Cp[VZ, conj[VWp], VWp], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZ, VZ, Ah, Ah], SSVV, 1, 1/2}, {hh, hh, Cp[VZ, VZ, hh, hh], 
   SSVV, 1, 1/2}, {conj[Hp], Hp, Cp[VZ, VZ, conj[Hp], Hp], SSVV, 1, 1}, 
  {conj[VWp], VWp, Cp[VZ, VZ, conj[VWp], VWp], VVVV, 1, 1}}, 
 {{Hp, Ah, Cp[conj[VWp], Hp, Ah], SSV, 1, 1}, 
  {bar[Fd], Fu, Cp[conj[VWp], bar[Fd[{gI1}]], Fu[{gI2}]], FFV, 3, 1}, 
  {bar[Fe], Fv, Cp[conj[VWp], bar[Fe[{gI1}]], Fv[{gI2}]], FFV, 1, 1}, 
  {bar[gWpC], gP, Cp[conj[VWp], bar[gWpC], gP], GGV, 1, 1}, 
  {bar[gP], gWp, Cp[conj[VWp], bar[gP], gWp], GGV, 1, 1}, 
  {bar[gZ], gWp, Cp[conj[VWp], bar[gZ], gWp], GGV, 1, 1}, 
  {bar[gWpC], gZ, Cp[conj[VWp], bar[gWpC], gZ], GGV, 1, 1}, 
  {Hp, hh, Cp[conj[VWp], Hp, hh], SSV, 1, 1}, 
  {VWp, hh, Cp[conj[VWp], VWp, hh], SVV, 1, 1}, 
  {VP, Hp, Cp[conj[VWp], VP, Hp], SVV, 1, 1}, {VZ, Hp, Cp[conj[VWp], VZ, Hp], 
   SVV, 1, 1}, {VWp, VP, Cp[conj[VWp], VWp, VP], VVV, 1, 1}, 
  {VZ, VWp, Cp[conj[VWp], VZ, VWp], VVV, 1, 1}, 
  {Ah, Ah, Cp[VWp, conj[VWp], Ah, Ah], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VWp, conj[VWp], hh, hh], SSVV, 1, 1/2}, 
  {conj[Hp], Hp, Cp[VWp, conj[VWp], conj[Hp], Hp], SSVV, 1, 1}, 
  {VP, VP, Cp[VWp, conj[VWp], VP, VP], VVVV, 1, 1/2}, 
  {conj[VWp], VWp, Cp[VWp, conj[VWp], conj[VWp], VWp], VVVV, 1, 1}, 
  {VZ, VZ, Cp[VWp, conj[VWp], VZ, VZ], VVVV, 1, 1/2}}}
