{{{Ah, Ah, conj[VWp[{lt3}]], VWp[{lt4}]}, {(I/2)*g2^2, g[lt3, lt4]}}, 
 {{Ah, Ah, VZ[{lt3}], VZ[{lt4}]}, {(I/2)*(g2*Cos[ThetaW] + g1*Sin[ThetaW])^2, 
   g[lt3, lt4]}}, {{Ah, Hp, conj[VWp[{lt3}]], VP[{lt4}]}, 
  {(g1*g2*Cos[ThetaW])/2, g[lt3, lt4]}}, 
 {{Ah, Hp, conj[VWp[{lt3}]], VZ[{lt4}]}, {-1/2*(g1*g2*Sin[ThetaW]), 
   g[lt3, lt4]}}, {{Ah, conj[Hp], VP[{lt3}], VWp[{lt4}]}, 
  {-1/2*(g1*g2*Cos[ThetaW]), g[lt3, lt4]}}, 
 {{Ah, conj[Hp], VWp[{lt3}], VZ[{lt4}]}, {(g1*g2*Sin[ThetaW])/2, 
   g[lt3, lt4]}}, {{hh, hh, conj[VWp[{lt3}]], VWp[{lt4}]}, 
  {(I/2)*g2^2, g[lt3, lt4]}}, {{hh, hh, VZ[{lt3}], VZ[{lt4}]}, 
  {(I/2)*(g2*Cos[ThetaW] + g1*Sin[ThetaW])^2, g[lt3, lt4]}}, 
 {{hh, Hp, conj[VWp[{lt3}]], VP[{lt4}]}, {(I/2)*g1*g2*Cos[ThetaW], 
   g[lt3, lt4]}}, {{hh, Hp, conj[VWp[{lt3}]], VZ[{lt4}]}, 
  {(-1/2*I)*g1*g2*Sin[ThetaW], g[lt3, lt4]}}, 
 {{hh, conj[Hp], VP[{lt3}], VWp[{lt4}]}, {(I/2)*g1*g2*Cos[ThetaW], 
   g[lt3, lt4]}}, {{hh, conj[Hp], VWp[{lt3}], VZ[{lt4}]}, 
  {(-1/2*I)*g1*g2*Sin[ThetaW], g[lt3, lt4]}}, 
 {{Hp, conj[Hp], VP[{lt3}], VP[{lt4}]}, 
  {(I/2)*(g1*Cos[ThetaW] + g2*Sin[ThetaW])^2, g[lt3, lt4]}}, 
 {{Hp, conj[Hp], VP[{lt3}], VZ[{lt4}]}, 
  {(-1/4*I)*(-2*g1*g2*Cos[2*ThetaW] + (g1^2 - g2^2)*Sin[2*ThetaW]), 
   g[lt3, lt4]}}, {{Hp, conj[Hp], conj[VWp[{lt3}]], VWp[{lt4}]}, 
  {(I/2)*g2^2, g[lt3, lt4]}}, {{Hp, conj[Hp], VZ[{lt3}], VZ[{lt4}]}, 
  {(I/2)*(g2*Cos[ThetaW] - g1*Sin[ThetaW])^2, g[lt3, lt4]}}}
