{{{Ah, Ah, Cp[hh, Ah, Ah], SSS, 1, 1/4}, 
  {bar[Fd], Fd, Cp[hh, bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[hh, bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[hh, bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {bar[gWp], gWp, Cp[hh, bar[gWp], gWp], GGS, 1, 1/2}, 
  {bar[gWpC], gWpC, Cp[hh, bar[gWpC], gWpC], GGS, 1, 1/2}, 
  {bar[gZ], gZ, Cp[hh, bar[gZ], gZ], GGS, 1, 1/2}, 
  {hh, hh, Cp[hh, hh, hh], SSS, 1, 1/4}, {conj[Hp], Hp, Cp[hh, conj[Hp], Hp], 
   SSS, 1, 1/2}, {conj[VWp], VWp, Cp[hh, conj[VWp], VWp], SVV, 1, 1/2}, 
  {VZ, VZ, Cp[hh, VZ, VZ], SVV, 1, 1/4}}}
