(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Standard Model",
  Authors -> {"N. Christensen", "C. Duhr", "B. Fuks"},
  Version -> "1.4.6",
  Date -> "15. 04. 2014",
  Institutions -> {"Michigan State University", "Universite catholique de Louvain (CP3)", "IPHC Strasbourg / University of Strasbourg"},
  Emails -> {"neil@pa.msu.edu", "claude.duhr@uclouvain.be", "benjamin.fuks@cnrs.in2p3.fr"},
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/StandardModel"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] ] == {{0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc13, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc14, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc16, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc19, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc20, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc22, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc24, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc27, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc28, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc30, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc32, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc34, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc36*SUNF[e3x2, e1x1, e2x1], -1/2*(GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/aS}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc38*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc38*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc38*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc39L*IndexDelta[e1x2, e2x2], (yb*Conjugate[CKM3x3]*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MB)}, {gc39R*IndexDelta[e1x2, e2x2], -1/2*(yt*Conjugate[CKM3x3]*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MT}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc40L*IndexDelta[e1x2, e2x2], (ydo*Conjugate[CKM2x1]*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{c, c}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MD)}, {gc40R*IndexDelta[e1x2, e2x2], -1/2*(yc*Conjugate[CKM2x1]*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MC}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc41L*IndexDelta[e1x2, e2x2], (ydo*Conjugate[CKM1x1]*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "R"] + MD*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MD)}, {gc41R*IndexDelta[e1x2, e2x2], -1/2*(yup*Conjugate[CKM1x1]*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{d, d}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MU}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc42L*IndexDelta[e1x2, e2x2], (ys*Conjugate[CKM2x2]*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{c, c}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MS)}, {gc42R*IndexDelta[e1x2, e2x2], -1/2*(yc*Conjugate[CKM2x2]*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MC}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc43L*IndexDelta[e1x2, e2x2], (ys*Conjugate[CKM1x2]*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "R"] + MS*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MS)}, {gc43R*IndexDelta[e1x2, e2x2], -1/2*(yup*Conjugate[CKM1x2]*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{s, s}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MU}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc44L*IndexDelta[e1x2, e2x2], -1/2*(yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {gc44R*IndexDelta[e1x2, e2x2], (yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc45L*IndexDelta[e1x2, e2x2], -1/2*(ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {gc45R*IndexDelta[e1x2, e2x2], (ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc46L*IndexDelta[e1x2, e2x2], -1/2*(ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {gc46R*IndexDelta[e1x2, e2x2], (ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc47*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}, {I*gc47*IndexDelta[e1x2, e2x2], ((-1/2*I)*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MB)}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc48*IndexDelta[e1x2, e2x2], ((-1/2*I)*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}, {I*gc48*IndexDelta[e1x2, e2x2], ((-1/2*I)*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MD)}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc49*IndexDelta[e1x2, e2x2], ((-1/2*I)*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}, {I*gc49*IndexDelta[e1x2, e2x2], ((-1/2*I)*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MS)}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "L"] + MB*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[4] , F[1] , -S[3] ] == {{gc53, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc54, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc55, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc56L, 0}, {gc56R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc57L, 0}, {gc57R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc58L, 0}, {gc58R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc59, 0}, {I*gc59, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc60, 0}, {I*gc60, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc61, 0}, {I*gc61, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc62L*IndexDelta[e1x2, e2x2], (CKM2x1*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MC)}, {gc62R*IndexDelta[e1x2, e2x2], -1/2*(CKM2x1*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{c, c}, {{}}, "L"] + MD*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MD}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc63L*IndexDelta[e1x2, e2x2], (CKM2x2*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "R"] + MC*FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(2*MC)}, {gc63R*IndexDelta[e1x2, e2x2], -1/2*(CKM2x2*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{c, c}, {{}}, "L"] + MS*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/MS}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc64L*IndexDelta[e1x2, e2x2], (CKM3x3*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{b, b}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MT)}, {gc64R*IndexDelta[e1x2, e2x2], -1/2*(CKM3x3*yb*(2*FR$delta[{MB}, {}] + MB*FR$deltaZ[{b, b}, {{}}, "R"] + MB*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MB}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc65L*IndexDelta[e1x2, e2x2], (CKM1x1*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{d, d}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MU)}, {gc65R*IndexDelta[e1x2, e2x2], -1/2*(CKM1x1*ydo*(2*FR$delta[{MD}, {}] + MD*FR$deltaZ[{d, d}, {{}}, "R"] + MD*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MD}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc66L*IndexDelta[e1x2, e2x2], (CKM1x2*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{s, s}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*MU)}, {gc66R*IndexDelta[e1x2, e2x2], -1/2*(CKM1x2*ys*(2*FR$delta[{MS}, {}] + MS*FR$deltaZ[{s, s}, {{}}, "R"] + MS*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/MS}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc67L*IndexDelta[e1x2, e2x2], (yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MC)}, {gc67R*IndexDelta[e1x2, e2x2], -1/2*(yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc68L*IndexDelta[e1x2, e2x2], (yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MT)}, {gc68R*IndexDelta[e1x2, e2x2], -1/2*(yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc69L*IndexDelta[e1x2, e2x2], (yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*MU)}, {gc69R*IndexDelta[e1x2, e2x2], -1/2*(yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc70*IndexDelta[e1x2, e2x2], ((-1/2*I)*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}, {I*gc70*IndexDelta[e1x2, e2x2], ((-1/2*I)*yc*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MC)}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc71*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}, {I*gc71*IndexDelta[e1x2, e2x2], ((-1/2*I)*yt*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MT)}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e1x2, e2x2], ((-1/2*I)*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}, {I*gc72*IndexDelta[e1x2, e2x2], ((-1/2*I)*yup*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*MU)}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MC}, {}] + MC*FR$deltaZ[{c, c}, {{}}, "L"] + MC*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MU}, {}] + MU*FR$deltaZ[{u, u}, {{}}, "L"] + MU*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*EL^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-1/2*I)*EL)/sw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*sw), 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/sw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*sw), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc91, 0}, {I*gc91, 0}, {I*gc91, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc93, 0}, {I*gc93, 0}, {I*gc93, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc94R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc95R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc96R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*EL^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc106, 0}, {(-I)*gc106, 0}, {(2*I)*gc106, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc111, 0}, {I*gc111, 0}, {I*gc111, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc112, 0}, {I*gc112, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc113, 0}, {I*gc113, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc114, 0}, {I*gc114, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc115*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc115*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc116*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc116*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc117*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc117*IndexDelta[e1x2, e2x2], ((2*I)/3)*EL*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc118*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc118*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc119*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc119*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc120*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {I*gc120*IndexDelta[e1x2, e2x2], (-1/3*I)*EL*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc121*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc121*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc122*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc122*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc123*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc123*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc124*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc124*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc125*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc125*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc126*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc126*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc127*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x1*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc128*IndexDelta[e1x2, e2x2], ((I/2)*CKM2x2*EL*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc129*IndexDelta[e1x2, e2x2], ((I/2)*CKM3x3*EL*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc130*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x1*EL*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc131*IndexDelta[e1x2, e2x2], ((I/2)*CKM1x2*EL*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc132*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM3x3]*(FR$deltaZ[{b, b}, {{}}, "L"] + FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc133*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x1]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc134*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x1]*(FR$deltaZ[{d, d}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc135*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM2x2]*(FR$deltaZ[{c, c}, {{}}, "L"] + FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc136*IndexDelta[e1x2, e2x2], ((I/2)*EL*Conjugate[CKM1x2]*(FR$deltaZ[{s, s}, {{}}, "L"] + FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw)}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc137, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc138, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc139, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc140, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc141, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc142, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc143L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc143R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc144L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc144R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc145L*IndexDelta[e1x2, e2x2], ((I/6)*EL*(3*cw^2 - sw^2)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc145R*IndexDelta[e1x2, e2x2], (((-2*I)/3)*EL*sw*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc146L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc146R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc147L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc147R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc148L*IndexDelta[e1x2, e2x2], ((-1/6*I)*EL*(3*cw^2 + sw^2)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2])/(cw*sw)}, {I*gc148R*IndexDelta[e1x2, e2x2], ((I/3)*EL*sw*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2])/cw}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc149, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc150, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc151, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc152L, 0}, {I*gc152R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc153L, 0}, {I*gc153R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc154L, 0}, {I*gc154R, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc13 -> -EL,
     gc14 -> EL,
     gc16 -> -EL,
     gc19 -> EL,
     gc20 -> (cw*EL)/sw,
     gc22 -> -((cw*EL)/sw),
     gc24 -> EL,
     gc27 -> -EL,
     gc28 -> -((cw*EL)/sw),
     gc30 -> (cw*EL)/sw,
     gc32 -> -((cw*EL)/sw),
     gc34 -> (cw*EL)/sw,
     gc36 -> -GS,
     gc38 -> GS^2,
     gc39L -> yb*Conjugate[CKM3x3],
     gc39R -> -(yt*Conjugate[CKM3x3]),
     gc40L -> ydo*Conjugate[CKM2x1],
     gc40R -> -(yc*Conjugate[CKM2x1]),
     gc41L -> ydo*Conjugate[CKM1x1],
     gc41R -> -(yup*Conjugate[CKM1x1]),
     gc42L -> ys*Conjugate[CKM2x2],
     gc42R -> -(yc*Conjugate[CKM2x2]),
     gc43L -> ys*Conjugate[CKM1x2],
     gc43R -> -(yup*Conjugate[CKM1x2]),
     gc44L -> -(yb/Sqrt[2]),
     gc44R -> yb/Sqrt[2],
     gc45L -> -(ydo/Sqrt[2]),
     gc45R -> ydo/Sqrt[2],
     gc46L -> -(ys/Sqrt[2]),
     gc46R -> ys/Sqrt[2],
     gc47 -> -(yb/Sqrt[2]),
     gc48 -> -(ydo/Sqrt[2]),
     gc49 -> -(ys/Sqrt[2]),
     gc53 -> ye,
     gc54 -> ym,
     gc55 -> ytau,
     gc56L -> -(ye/Sqrt[2]),
     gc56R -> ye/Sqrt[2],
     gc57L -> -(ym/Sqrt[2]),
     gc57R -> ym/Sqrt[2],
     gc58L -> -(ytau/Sqrt[2]),
     gc58R -> ytau/Sqrt[2],
     gc59 -> -(ye/Sqrt[2]),
     gc60 -> -(ym/Sqrt[2]),
     gc61 -> -(ytau/Sqrt[2]),
     gc62L -> CKM2x1*yc,
     gc62R -> -(CKM2x1*ydo),
     gc63L -> CKM2x2*yc,
     gc63R -> -(CKM2x2*ys),
     gc64L -> CKM3x3*yt,
     gc64R -> -(CKM3x3*yb),
     gc65L -> CKM1x1*yup,
     gc65R -> -(CKM1x1*ydo),
     gc66L -> CKM1x2*yup,
     gc66R -> -(CKM1x2*ys),
     gc67L -> yc/Sqrt[2],
     gc67R -> -(yc/Sqrt[2]),
     gc68L -> yt/Sqrt[2],
     gc68R -> -(yt/Sqrt[2]),
     gc69L -> yup/Sqrt[2],
     gc69R -> -(yup/Sqrt[2]),
     gc70 -> -(yc/Sqrt[2]),
     gc71 -> -(yt/Sqrt[2]),
     gc72 -> -(yup/Sqrt[2]),
     gc91 -> EL^2,
     gc93 -> -(EL^2/sw^2),
     gc94R -> -ye,
     gc95R -> -ym,
     gc96R -> -ytau,
     gc106 -> -((cw*EL^2)/sw),
     gc111 -> (cw^2*EL^2)/sw^2,
     gc112 -> -EL,
     gc113 -> -EL,
     gc114 -> -EL,
     gc115 -> (2*EL)/3,
     gc116 -> (2*EL)/3,
     gc117 -> (2*EL)/3,
     gc118 -> -1/3*EL,
     gc119 -> -1/3*EL,
     gc120 -> -1/3*EL,
     gc121 -> GS,
     gc122 -> GS,
     gc123 -> GS,
     gc124 -> GS,
     gc125 -> GS,
     gc126 -> GS,
     gc127 -> (CKM2x1*EL)/(Sqrt[2]*sw),
     gc128 -> (CKM2x2*EL)/(Sqrt[2]*sw),
     gc129 -> (CKM3x3*EL)/(Sqrt[2]*sw),
     gc130 -> (CKM1x1*EL)/(Sqrt[2]*sw),
     gc131 -> (CKM1x2*EL)/(Sqrt[2]*sw),
     gc132 -> (EL*Conjugate[CKM3x3])/(Sqrt[2]*sw),
     gc133 -> (EL*Conjugate[CKM2x1])/(Sqrt[2]*sw),
     gc134 -> (EL*Conjugate[CKM1x1])/(Sqrt[2]*sw),
     gc135 -> (EL*Conjugate[CKM2x2])/(Sqrt[2]*sw),
     gc136 -> (EL*Conjugate[CKM1x2])/(Sqrt[2]*sw),
     gc137 -> EL/(Sqrt[2]*sw),
     gc138 -> EL/(Sqrt[2]*sw),
     gc139 -> EL/(Sqrt[2]*sw),
     gc140 -> EL/(Sqrt[2]*sw),
     gc141 -> EL/(Sqrt[2]*sw),
     gc142 -> EL/(Sqrt[2]*sw),
     gc143L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc143R -> (-2*EL*sw)/(3*cw),
     gc144L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc144R -> (-2*EL*sw)/(3*cw),
     gc145L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc145R -> (-2*EL*sw)/(3*cw),
     gc146L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc146R -> (EL*sw)/(3*cw),
     gc147L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc147R -> (EL*sw)/(3*cw),
     gc148L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc148R -> (EL*sw)/(3*cw),
     gc149 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc150 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc151 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc152L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc152R -> (EL*sw)/cw,
     gc153L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc153R -> (EL*sw)/cw,
     gc154L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc154R -> (EL*sw)/cw};

